# Convenience ClusterRole for cluster admins to delegate admin access on cronjobmonitors. Not used by cronguard itself.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cronguard
    app.kubernetes.io/managed-by: kustomize
  name: cronjobmonitor-admin-role
rules:
- apiGroups:
  - monitoring.cronguard.io
  resources:
  - cronjobmonitors
  verbs:
  - '*'
- apiGroups:
  - monitoring.cronguard.io
  resources:
  - cronjobmonitors/status
  verbs:
  - get
