# Convenience ClusterRole for cluster admins to delegate edit access on cronjobmonitors. Not used by cronguard itself.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cronguard
    app.kubernetes.io/managed-by: kustomize
  name: cronjobmonitor-editor-role
rules:
- apiGroups:
  - monitoring.cronguard.io
  resources:
  - cronjobmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.cronguard.io
  resources:
  - cronjobmonitors/status
  verbs:
  - get
