---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.cronguard.io
  resources:
  - cronjobmonitors
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.cronguard.io
  resources:
  - cronjobmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.cronguard.io
  resources:
  - cronjobmonitors/status
  verbs:
  - get
  - patch
  - update
