apiVersion: v2
name: cronguard
description: SLO-style observability operator for Kubernetes CronJobs
type: application
version: 0.3.3
appVersion: "0.3.3"
kubeVersion: ">=1.28.0-0"
home: https://github.com/dmazhukov/cronguard
sources:
  - https://github.com/dmazhukov/cronguard
keywords:
  - kubernetes
  - operator
  - cronjob
  - prometheus
  - sre
  - slo
  - monitoring
maintainers:
  - name: Dmitrii Zhukov
    email: dmitry0983@gmail.com
    url: https://github.com/dmazhukov
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - Initial Helm chart release
  artifacthub.io/links: |
    - name: GitHub
      url: https://github.com/dmazhukov/cronguard
    - name: OCI
      url: oci://ghcr.io/dmazhukov/charts/cronguard
