apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cronguard.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cronguard.labels" . | nindent 4 }}
